# -*- coding:utf-8 -*-



def main():
    s1 = '''CACCCCCCGGGGATGGCACAAGTCTGGGAACGAAACGCTCCGAACGAAGAGCAATGTCGG
AGGTCGGGGCGGATCGAGGTGGGATACTCTGAAATATTTTTGAGTATGATACTGCGTTCG
CGGTGCCTATATACGCTGTGAAAAATGCTATTTTTTTATAGATCCGATGGAATATGTATT
CGACTTTAAGGAGGCCCCGTCAGCAGATACAACATCGGTAGTGTAATTCTACCAAAGCAG
CGCTATGCTCTAGTCAGTCAACGGTTGGAGCCCTCGCGCGAAGAATGTGTAAGATCATTT
AGAGTATTATGGGGCCACCTCAACCCCATGGTCGCACATGGTGTATTCCCAAGGTACAAT
CCGGAGGCTGATTGGAGCTGACCGCATGAGACATTATAATGGATGTCATAGTCCGCTCTG
CGACAGATGCTATATATACCAAAGGATGACTCCCGGGCAGAGGTTTGTGTTTCCGTAGCT
TACTACCTCGCTACCAACCTATTCGGTATAATAAAGGTTTTCTACTTTCCCGAGCGTTGT
AGGGTGTATTGTTGGTACATCCGGCGATACAATTATCTGGCGTCCATCATCGGCAGCGCT
GTGACCAATGGTGATGAAGAAAACTAACATCGCATGTAGTCCGGGGAGTGATAATGCGGA
TCAAGTGGCTACCTGATAGTCAAGCAAGACAAACGCATCTAGATACTGCGGATTAGGGAG
TTACATAGCAAGACGCAGCCGAAGGGTATGACGGGAGGCAGTCGTCGATAAACCTAGCCT
CTGCCGTCCGTAGATTTCTTGGAACTACGAGAGACGCACATTATGTTGGCTCGAGTCGAA
TAGTGGTCGGTCGCCGTGCACTCTATACGCTACATCCGGGGAGTTCTCGTGAAATATTCA
GTCTCTGCTGAGCGCCGGCCTCCATATGCATACACCTCCATCAAGAGACGTTTCATGGCG
CCCCGCTCCCCGTCTATAAGTGAGGGTGTA'''.replace("\n","")
    s2 = '''CGCCCCCCGAAGCCGGCATAAGTCTTGGTACTACACTTTCCGAGCAAAGAGAAACATCAA
TGCCCCGGGCGAATCAAGACAGTATACTCTTAAATTTCGCCGCACACAATACTGTGTCTG
AGGTGCCTATATACGATGTAAAAAGAGCGAACCTCATCTAGATGCAATAGGATACAAGTG
CGCCTCTAAAGCGGTCCCGTCAGCAGAAACACCAGCAGTATTGTGATTCTACCAAAGTAT
CACTATGATCACGTTGGTCGACGGTTGGCGCCCTGGTGCGAACAGCGGTTAGAATCACTT
AGGGTATTACGGGGCCACTCCGACCATACAGTTACACGTGGCCTTCTCCCGGGGTGCAAT
TCGGAGGCTGACCCGGGTTAACCGCAAGAGACATCTTAATGGATGCCGAGAACCGTTCTG
CAACAGAGAATTGATATATCAAAGGGCTATCCCAGGGCAGAGATTTGTGTGCCCGTAGTT
CACTACCCTTCGTCCAACCTGTTCGGTATGACGAGAGTTTCCTACTATCCCGAGCGTTAT
CAGATGTATTGTTGGTGTATCCGACGACGGGATTGGGCGGCGTCCGCCAATGGCAGCGCA
GTGACCACTGGATATAAAAAAAACTAACATTGTATCTACTTAGGGGCATGAAGATGCAGT
GCAAGCAGCTCCCTGACAGTCAGGCGAGACAAAAGCATCTAGATGTTGCCGACTAGGGAT
CCGCACAGCAAGAAGAGATCGGAGGACATAACGGGTGCCGGTCGTCAATAGACCTAGTTT
TTACCGCACGTATATTTAATGAAAATGCGAGAAACGCACACTATGTTGATTCGAGTTGGA
CAGTGGTTGGATCTGATATGGCCTATAACCTTCGGCCAGAGATTGCTTGTGAAATCCTTA
ATCTCTGCCGTGTGCTGGACTTCATTCTCATACGCCTTCAACACTGGATGTTCTGTGGCC
CTCCGCTCCCTGTGCACAAATGATGGTATC'''.replace("\n","")

    transitionsmap = [("A","G"),("G","A"),("C","T"),("T","C")]
    transversionsmap = [("A","C"),("C","A"),("T","G"),("G","T")
        ,("A","T"),("T","A"),("C","G"),("G","C")]

    transitions = 0
    transversions = 0
    for i in range(len(s1)):
        pos = (s1[i],s2[i])
        if pos in transitionsmap:
            transitions += 1
        elif pos in transversionsmap:
            transversions += 1
        else:
            pass

    print(transitions/transversions)


if __name__ == "__main__":
    main()