# -*- coding:utf-8 -*-
import re
from itertools import *

def main():
    s = '''CGAGTAAAAAGCGATCCAAATCCGTGAAGTAATTGGCGGCCTTGACCAACGGTGGGTGGA
TCTTTGAGTATGCGCCCTGTAGCACGCTGCAGCGGTCGAACCTCACCAGAATAATGGGAT
CACCTGTCCGATGCTCCTCGGAGGTGCTGGCGTCAGTGTATGGACGAATAGCGCGCGGGA
GCCTGCGCAGAAGCGATAATCGTTGGTGTTCATTACGGGATGTGGGAATCTGGCCCGTAT
TGCCATAAAACCGTAGGAAACAGTTGACCAACGGATTGCAGAAATTCGAAATACGATACT
TTTTCCATGCGAAAGCTTAGCTTCCATGGCTTGTTTCTGCAACAGCTACTGTACCAGTTA
AAGGCACACGCACCTCTGGACATTGCCAACCTAGGTTAAATTTAGGCTTTCTGCGCCATT
GTCCGACTCGGAGGATAAACTATTCAGTACGCTGCAGAGTCCCAATGGGCGAGGAGAATA
TGGCACCTGCAGGCCAATTCACCCAATGAATAGTCGCAGGTAATACAATACTCAAAGAGC
TCAAAGTCAAACGACGGTCTTCAGAGACCCGTTATAGAGAGACCAGCTTTGTTACCACGT
CGCCAGATTGTTCGGGTGCACACCATCCGTGCTCGCAAATGGACGGCGTCTTCAAAAGCG
GCTATCGCTGTGCAGGCACTTCCCGCGGTTAGGCTGGTGTTGTCGTACCCGTAAGACGGA
TCCCTTCTAACCCGTAACTTACGATTCCTATCGCAGGACGCGACACGGGATTAGATGTGC
CTCGTCCGCGATATGCCCCTCAGTTAGT'''.replace("\n",'')
    t = "ACCCCCTTTTGCGGAGTATTCGCTGCAACTAGGAGATAC"
    indmap = []
    for i, ti in enumerate(t):
        if i == 0:
            indmap.append([m.start()+1 for m in re.finditer(ti, s)])
        else:
            indmap.append([m.start() + 1 for m in re.finditer(ti, s) if m.start() + 1>min(indmap[i-1])])

    for prod in product(*indmap):
        if tuple(prod) == tuple(sorted(prod)):
            print(" ".join([str(i) for i in prod]))
            break

def another():
    a = '''CGAGTAAAAAGCGATCCAAATCCGTGAAGTAATTGGCGGCCTTGACCAACGGTGGGTGGA
    TCTTTGAGTATGCGCCCTGTAGCACGCTGCAGCGGTCGAACCTCACCAGAATAATGGGAT
    CACCTGTCCGATGCTCCTCGGAGGTGCTGGCGTCAGTGTATGGACGAATAGCGCGCGGGA
    GCCTGCGCAGAAGCGATAATCGTTGGTGTTCATTACGGGATGTGGGAATCTGGCCCGTAT
    TGCCATAAAACCGTAGGAAACAGTTGACCAACGGATTGCAGAAATTCGAAATACGATACT
    TTTTCCATGCGAAAGCTTAGCTTCCATGGCTTGTTTCTGCAACAGCTACTGTACCAGTTA
    AAGGCACACGCACCTCTGGACATTGCCAACCTAGGTTAAATTTAGGCTTTCTGCGCCATT
    GTCCGACTCGGAGGATAAACTATTCAGTACGCTGCAGAGTCCCAATGGGCGAGGAGAATA
    TGGCACCTGCAGGCCAATTCACCCAATGAATAGTCGCAGGTAATACAATACTCAAAGAGC
    TCAAAGTCAAACGACGGTCTTCAGAGACCCGTTATAGAGAGACCAGCTTTGTTACCACGT
    CGCCAGATTGTTCGGGTGCACACCATCCGTGCTCGCAAATGGACGGCGTCTTCAAAAGCG
    GCTATCGCTGTGCAGGCACTTCCCGCGGTTAGGCTGGTGTTGTCGTACCCGTAAGACGGA
    TCCCTTCTAACCCGTAACTTACGATTCCTATCGCAGGACGCGACACGGGATTAGATGTGC
    CTCGTCCGCGATATGCCCCTCAGTTAGT'''.replace("\n", '')
    b = "ACCCCCTTTTGCGGAGTATTCGCTGCAACTAGGAGATAC"
    res = []
    i = 0
    for c in b:
        i = (i + a[i:].index(c)) + 1
        res.append(str(i))
    print(' '.join(res))

if __name__ == "__main__":
    another()