# -*- coding:utf-8 -*-

def edit_distance(str1, str2):
    m, n = len(str1), len(str2)
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    for i in range(m + 1):
        for j in range(n + 1):
            if i == 0:
                dp[i][j] = j
            elif j == 0:
                dp[i][j] = i
            elif str1[i - 1] == str2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = 1 + min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])

    return dp[m][n]

def main():
    str1 = '''MLDVKTLTHHLQWIHAKQKLAYIYWACTLLNLQWFNPWFHAALNTDCYLFAHPTHYWCQS
QSTPHKVWRCLQIKMFEWIKTYKIGTAHSLSRYNKSYGGRPRFANTEQSELRPEHPKRNF
TVRQFPAIHKETQITCHVLHVCCHWIRNFCHVWDWLGDQRWEDLACMYYYMHWNNNHIHN
ENQQFFLHWSPKIVQDCIKGMEKHWMDSITLCPAYELNEAIWVSHLGLPAFCCAENLLKH
VDQTAIMDSQIECTTLIREKTIAPPTDEDYNTIVDHFMHLAEFTAEEDWRNYTDRGDWWP
GNFRADMNHLLIEHECHEMKLKGHYGGFAAGQPTYVWRIGAMFDTWWQSTGIYQGEIPPL
DRLWVSFDYPSLLHLPWWDMIICKHDAFFGANGLLIIAWWVGLECFSQAIISINWANWPI
VEMHSLLWKKEIVELNDEIDHQNIVCRTLTEVGPVQQVHIAHNWSNTNSVEQFHWTPIIC
APDCIMGIWRYKCESWQEIGSNNWMRDKYCISSTSYPDDEITCTWFGLNWDNAKYVSMNP
YYNILNMIWQVVKDYYIKEKMGIMTSIDACNKWQNFTTFFSHLGLLWNIANLHMMQLKSE
LKLAMDVVLGIDRMKSGMPDSFQDAFFFMHDYGEGGMVPITWELYRDDWMMACLEVYIFG
RCFMVVWKFGCTPLQTDCHIFFWLFITLDPERRLCFAAPATICEGVLPYQNQPCWVREND
SNFSLKKGGDPLWVPAFWMQKQCQFPKPYKGSEKWLAFKTN'''.replace("\n","")
    str2 = '''MLDVKTHVNTHIQKLAYFEVKKHQKYLACTWWHVWHAALNTDCYLFAHQHTPHKVWCCKA
GVLMNEDCTYKAGPAHSSYWFDGGRPRFANCEQIRSVMMELARPEKRRPKKQPTMNFIVR
QFPAPCPQLHVCCHWIIMRAAHRHVWDWLGDQRWEMYYYMHWNNNHIHNERMAEQQVFLH
WSPKIVQDCIKFHEKIWMDSITLYPAYSWDSSIFWLGLPAFCCAENQLKRMVNQTAIMDS
QIECWYTLIGDELTCTNRCDVLIVDHFMHLAEFTAEEDWRNYNFNADMNHLAIEHECHEM
KLKDIDKEDHHAGQPTYVWRIGAMFDTWQQSTGIYQGEIPPLDRCWHLFDYPSCRIFNMM
LKFHMPWWHDAFFGANELIIAIVWVGLECFSQAIISDCLYYNWHSLLWKKEIVELMDEID
HQNIDDPNQCEVCATLTEVGAMQQVEIFHCEHFHWTPIYEDDGEMSICAPDCIMYECESW
QEIGSNNWMRDKYCIKLASGSCSTSYPDIEITMPCIIWFGLNWKFEYIMNPYYNILNMIW
QVIQPSDNKDYYIKTEETNIMTQRPAGKYIDACNKWQNFTLLWSSWLHVMQLKSELKLNM
CVVLGIMFSSMPSSFQDAFFFMHDYNEGGLKYSVYIFPGGRCFMVVWKFGRTPLQTFITL
DPAAICCSELPYQWVRENDRWFSCYKMDPLWVPAFWMQKQCQFPKPYKGSEKCILAFKYN'''.replace("\n","")
    print(edit_distance(str1, str2))


if __name__ == "__main__":
    main()