# -*- coding:utf-8 -*-

def main():
    a = "CGACGGGAAACCACTCCCGTAAAACCGGTACACCTACAAAGTGACCAGTTGGCCTTTAGAGGGCGTGCAAGTTTTGCAGGTAATATAAGTATTTCGATCTCGATGGATGGTTCAGACTTGACCCACCACAGGTGAGGTCTCACCGGACCGACGGAGTCAAGCCTACAGATATCTCCTCCGCCCGAGATTACCTAATACAGCTCTTAAGTGAAATAAAATATACTGCGACCAAACAGGTGCGGAACATCCGCATATGGAACACAGATCCTCTCTCGGTAACGCATTTGGCCATCATGCCAACTCAGCCACGTAGTTCCCAAAACTAAACAGGTAAGTACTAGCCATGCAACCCCAGAACGCACCGAAGATAAATAACGAGAATGGACCATCATAGAACTTTGGTGAGTAAAACGCCAGTAGCTTCCAGACTGGAGAGTGACATACGGTCGCGGCTGCGGTAACACCACAGCCCCTACTTTTGACTACGAACTTCACACGAATCCCCGAATTGACCGTACACCCCTTCCCTTTCGAAGAGATGTCATCGAAGTGAGGCGGAGCTAAGAATCGCGGATGCTGGCTGCATGTCTCGTAGGGTGGACATGTAAGACTCCTTCCAATATGTGTCCCTTTCCCCACCTTCTAAAAGTCTCCTACACCAATGTACATACTCAGGGAACGCGGGAGTTCGAGGCTTCTGGGATGCTGGCCAATTCAGTTGCTTCGACGTCCTAAAGGTTGGGACCATGGCGCCACTTATCGGTGTAGTTAAAACTGGGCTACCGGGCTTTAACTCTGGTCTCTTTACCCGCCGTCCTCAGAGTGCAAAGTCGTCGCTGCGACGCGAACCTCTTATTAGACCTGTTAGCATTCCCCTG"
    elemap = {"A":"T","T":"A","C":"G","G":"C"}
    r = [elemap[i] for i in a]
    r.reverse()
    r = "".join(r)
    print(r)
if __name__ == "__main__":
    main()