# -*- coding:utf-8 -*-
import re

def solv1():
    input_str = "TGTGGAGAGGCGGAGAGGTTTAGGAGAGGGGAGAGGCTGAGAGGAGAGGTGGAGAGGAGGGAGAGGGGAGAGGTGGGAGAGGGGAGAGGCGGAGAGGTGGAGAGGGGGAGAGGTGTGAGCCCTAAAAGGAGAGGGGAGAGGTGGAGAGGGAAGTGGGAGAGGGCCGCCAGGAACCTATTAGTCGGAGAGGCTAGTTGGAGAGGTTCGTGGAGAGGTGTTGGAGAGGGGGTCGCTCAGGCTTCCGCGGGAGAGGGATCGGAAGATCCATTTCGCTGGAGAGGAGGAGGCCGGAGAGGCTTCTCGCGAGGAGAGGTGGAGAGGAGTAGGAGAGGCGGAGAGGGAATACCTTACTGAGGAGAGGGGAGAGGAGGAGAGGCAGGAGAGGTGGGAGAGGTGGGAGAGGGGAGAGGAGTTGGAGAGGCCGGAGAGGATCTAGGAGAGGGCGGAGAGGAGGAGAGGCGGAGAGGATGCCCGGGGAGAGGTGGAGAGGAGTGCCCGGAGAGGCGTGGAGAGGCTAGGAGAGGGGAGAGGGGAGAGGTGGAGAGGAGGAGAGGGGGAGAGGGGAGAGGCTTGGAGAGGGGAGAGGAATAAAGGGGAGAGGTCCCAGGAGAGGGGGGAGAGGCGGGAGAGGGGAGAGGGGGGAGAGGCTTTTAGGAGAGGGGGAGAGGCGGAGAGGGGAGAGGGCTGACGTCGGAGAGGGGAGAGGGGAGAGGCGGAGAGGGGAGAGGGGGAGAGGCCCTGGAGAGGGGGAGAGGCAGGGAGAGGGGAGAGGGTACGGAGAGGTATGAACGGAGAGGGGAGAGGGGAGAGGGGGGAGAGGTCACGGAGAGG"
    search_str = "GGAGAGGGG"
    r = [m.start()+1 for m in re.finditer('(?=%s)' % search_str, input_str)]
    print(str(r)[1:-1].replace(',',' '))

def solv2():
    input_str = "TTTCTAGAAACAGCTGCGAGCTGCGATAGGCTGCGAGCTGCGAGCTGCGAGATGGCTGCGATGCTGCGATTGGCTGCGAGCTGCGAGCTGCGACATGATGCTGCGAAGTGAGTGCTGCGAGGCTGCGATGCTGCGAGGCTGCATTCACGCTGCGAGCTGCGATCGCTGCGAACGTTGTCGGCTGCGATACAAGCTGCGAGCTGCGATTGGGCTGCGAAGCTGCGAGCTGCGAAGCTGCGACCCCGCTGGGACTCGGCTGCGAGCTGCGAGCTGCGAGTGCTGCGAGCTGCGAGCTGCGAAGCTGCGACGGCTGCGAGGCTGCGAGCTGCGAATTGAGCTGCGAGCAGAAGCTGCGAGCTGCGATTTGCTGCGACGCTGCGAGCTGCGATGATCACTTTGCGCTGCGATGCTGCGACTGGCTGCGAGCTGCGAGCTGCGAGCTGCGACTGCTGCGACGCTGCGAGCTGCGAGCGCTGCGAATAGCTGCGATGCTGCGACATGGGCTGCGACGCTGCGACTGAAGTGCTGCGATTAGTCCAGCTGCGAGCACGCTGCGATCGAGAGGCTGCGAGGCTGCGAAATATTGTCCTGCTGCGAAGCTGCGAGCTGCGAAGACGCTGCGACCGCTGCGAGCGCTGCGAAGCCCTGCTGCGACCGGGCTGCGAGTTCCCAAACGCTGCGAGCTGCGAGCTGCGAGCTGCGACTAAATACGAGCTGCGAGGCTGCGAGGCTGCGATGGCGCTGCGAGCTGCGACTGGCTGCGAGCTGCGAAAGCTGCGACGCGCGTTGCTGCGAATTGGCTGCGAGGCCTGCTGCGAGCTGCGAGCTGCGAAGGCTGCGATTCCCGCTGCGAGCTGCGACGCTGCGAGCTGCGAAG"
    search_str = "GCTGCGAGC"
    r = []
    start = 0
    while 1:
        idx = input_str.find(search_str)
        if idx!=-1:
            r.append(idx+1+start)
            input_str = input_str[idx+1:]
            start += idx+1
        else:
            break
    print(r)


if __name__ == "__main__":
    solv1()